// Branded HTML export.
//
// Approach:
// 1. Clone the <main> content of the current page
// 2. For each <canvas> (ECharts), serialize to data URL and swap in an <img>
// 3. Strip interactive-only elements (floating chat, inputs, buttons marked no-export)
// 4. Embed the app's stylesheets (Tailwind output) so the clone renders with
//    the same styling when opened standalone
// 5. Wrap in a branded header + footer and trigger a file download

export async function exportPageAsHtml(pageTitle: string): Promise<void> {
  const main = document.querySelector('main');
  if (!main) throw new Error('No <main> element to export');

  // Step 1: capture canvas pixels BEFORE cloning (cloned canvases are blank)
  const originalCanvases = Array.from(main.querySelectorAll('canvas')) as HTMLCanvasElement[];
  const canvasDataUrls: (string | null)[] = originalCanvases.map((c) => {
    try {
      // White background fallback so transparent charts look right when inlined
      return c.toDataURL('image/png');
    } catch {
      return null;
    }
  });
  const canvasSizes = originalCanvases.map((c) => ({
    width: c.offsetWidth || c.width,
    height: c.offsetHeight || c.height,
  }));

  // Step 2: clone and replace canvases with imgs
  const clone = main.cloneNode(true) as HTMLElement;
  const cloneCanvases = Array.from(clone.querySelectorAll('canvas')) as HTMLCanvasElement[];
  cloneCanvases.forEach((cc, i) => {
    const url = canvasDataUrls[i];
    if (!url || !cc.parentElement) return;
    const img = document.createElement('img');
    img.src = url;
    img.alt = 'chart';
    img.style.width = canvasSizes[i].width + 'px';
    img.style.height = canvasSizes[i].height + 'px';
    img.style.display = 'block';
    img.style.maxWidth = '100%';
    cc.parentElement.replaceChild(img, cc);
  });

  // Step 3: remove interactive / transient elements from the clone
  clone.querySelectorAll('[data-no-export], button, input, select, textarea, details > summary ~ pre').forEach((el) => {
    el.remove();
  });
  // Drop tabbing strips and `hover:` ring artifacts from Management layout
  clone.querySelectorAll('[role="tablist"], nav').forEach((el) => {
    if (!el.closest('[data-keep-nav]')) el.remove();
  });

  // Step 4: gather the app's CSS so the standalone document styles the clone
  const css = await gatherAppCss();

  // Step 5: wrap and trigger download
  const date = new Date();
  const stamp = date.toLocaleString();
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${esc(pageTitle)} — Breeze GA4 Analytics</title>
<style>${css}

/* Export-document overrides */
html, body { background: #ffffff !important; color: #1a1f29 !important; height: auto !important; }
body { padding: 0 !important; margin: 0 !important; font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; }
.__export-wrap { max-width: 1280px; margin: 0 auto; padding: 32px 40px 48px; }
.__export-header { display: flex; align-items: center; gap: 16px; padding-bottom: 18px; border-bottom: 1px solid #e4e7ec; margin-bottom: 28px; }
.__export-header .__logo { width: 44px; height: 44px; border-radius: 10px; background: #3b5bdb; color: #fff; display: flex; align-items: center; justify-content: center; font-weight: 800; font-size: 16px; letter-spacing: 0.5px; }
.__export-header h1 { font-size: 22px; margin: 0 0 2px 0; font-weight: 700; color: #1a1f29; }
.__export-header .__meta { color: #5c6473; font-size: 12px; font-family: ui-monospace, "SF Mono", Menlo, monospace; }
.__export-footer { margin-top: 56px; padding-top: 16px; border-top: 1px solid #e4e7ec; text-align: center; color: #8a93a3; font-size: 11px; }
.__export-footer a { color: #5c6473; text-decoration: none; }

/* Any fixed positioning in the app turns into normal flow in the report */
.fixed { position: static !important; }
main { padding: 0 !important; max-width: none !important; }
</style>
</head>
<body>
<div class="__export-wrap">
  <div class="__export-header">
    <div class="__logo">G4</div>
    <div>
      <h1>${esc(pageTitle)}</h1>
      <div class="__meta">Breeze GA4 Analytics · Exported ${esc(stamp)}</div>
    </div>
  </div>
  ${clone.outerHTML}
  <div class="__export-footer">
    Generated by Breeze GA4 Analytics on ${esc(stamp)}.
    This is a static snapshot — data will not update after export.
  </div>
</div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `breeze-ga4-${slug(pageTitle)}-${date.toISOString().slice(0, 10)}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 2_000);
}

/** Collect all of the app's <link rel="stylesheet"> and <style> contents. */
async function gatherAppCss(): Promise<string> {
  const parts: string[] = [];
  const links = Array.from(document.querySelectorAll('link[rel="stylesheet"]')) as HTMLLinkElement[];
  for (const l of links) {
    if (!l.href) continue;
    try {
      const res = await fetch(l.href);
      if (res.ok) parts.push(await res.text());
    } catch {
      // Same-origin only; skip anything blocked by CORS
    }
  }
  const styles = Array.from(document.querySelectorAll('style')) as HTMLStyleElement[];
  for (const s of styles) {
    if (s.textContent) parts.push(s.textContent);
  }
  return parts.join('\n');
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'report';
}
